export const PROJECTS = [
  [
    'NNplanner',
    'Planning and Management Service for Nutritionists',
    '/assets/portfolio/nnplanner-logo.png',
    'https://github.com/devping-kr/NNplanner-FE',
    'https://nnplanner.com',
    '#00A86B',
  ],
  [
    'GGF Good Game Friends',
    'Game community website for gamers',
    '/assets/portfolio/ggf-logo.png',
    'https://github.com/sprint-team3/GGF',
    'https://good-game-friends.vercel.app/landing',
    '#ADFF00',
  ],
  [
    'GGF UI',
    'Neon green theme React UI Library',
    '/assets/portfolio/ggf-ui-logo.png',
    'https://github.com/sprint-team3/GGF-Design-System',
    'https://www.npmjs.com/package/ggf-ui?activeTab=readme',
    '#852DFF',
  ],
  [
    'Lim-log',
    'Making blog with Next.js',
    '/assets/blog/authors/profile_pixel.avif',
    'https://github.com/grapefruit13/lim-log',
    'https://lim-log.vercel.app/',
    '#0f172a',
  ],
  [
    'TickyTocky',
    'Team task and schedule management service',
    '/assets/portfolio/tickytocky-logo.png',
    'https://github.com/TickyTocky/TickyTocky',
    'https://ticky-tocky.vercel.app/',
    '#37E8B4',
  ],
];
